<?php

//装饰模式
//场景 一个人穿衣服
class People {
    public $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function dress()
    {
        echo '我叫'.$this->name . '我要开始穿衣服了';
    }
}

//衣服抽象类
class Clothes {

    /**
     * @var People
     */
    public $people;

    public function bindPeople($people)
    {
        $this->people = $people;
    }

    public function dress()
    {
        if (!is_null($this->people)) {
            $this->people->dress();
        }
    }
}

//帽子
class Hat extends Clothes {

    public function dress()
    {
        parent::dress(); // TODO: Change the autogenerated stub
        echo '带帽子';
    }
}

//夹克
class Jacket extends Clothes {

    public function dress()
    {
        parent::dress(); // TODO: Change the autogenerated stub
        echo '穿夹克';
    }
}

//裤子
class Pants extends Clothes {

    public function dress()
    {
        parent::dress(); // TODO: Change the autogenerated stub
        echo '穿裤子';
    }
}

//鞋子
class Shoes extends Clothes {

    public function dress()
    {
        parent::dress(); // TODO: Change the autogenerated stub
        echo '穿鞋子';
    }
}

$name = 'zjw';//名字
$people = new People($name);
$hat = new Hat();
$jacket = new Jacket();
$shoe = new Shoes();
$hat->bindPeople($people);
$jacket->bindPeople($hat);//戴帽子
$shoe->bindPeople($jacket);//穿夹克
$shoe->dress();//穿鞋